### ISSUE TITLE
Codes not fully implemented

### ISSUE THREAD

**Issue by jjong0225** [HICL-SYSU/DCTN#1]
According to train code, the network name 'DCTN' is required for training. but i cannot find it within any files you provide.
and the CPR function has some errors(for example, the wrong indent at line 596 in model.py). 
I guess the codes is out dated. Could you please check this?

**Comment by HICL-SYSU** [comment]
Thanks for your feedback, we will update our code again after rechecking. May take some time to perfect the codes




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HICL-SYSU/DCTN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月2日(星期五) 下午4:29
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[HICL-SYSU/DCTN] Codes not fully implemented (Issue #1)





 
According to train code, the network name 'DCTN' is required for training. but i cannot find it within any files you provide.
 and the CPR function has some errors(for example, the wrong indent at line 596 in model.py).
 I guess the codes is out dated. Could you please check this?

**Comment by jjong0225** [comment]
Thank you for your kindness! I hope that i can get it soon.

**Comment by jjong0225** [comment]
I checked the all the updated codes. i really appreciate your feedback.
however, the "Guider" are still missing. can you check it?
